### Create a new transaction
POST http://localhost:5000/api/transactions/addTransaction
Content-Type: application/json

{
    "amount": 1000,
    "date": "2025-02-19",
    "description": "Grocery shopping",
    "category":"Food"
} 

### Get all Transactions
GET http://localhost:5000/api/transactions/getTransaction

### Edit the transaction
PUT http://localhost:5000/api/transactions/updateTransaction/67b62c8ee6d42061caf7851a
Content-Type: application/json

{
     "amount": 1000,
    "date": "2025-02-19",
    "description": "Grocery shopping",
    "category":"Food"

}

### Delete a transaction
DELETE http://localhost:5000/api/transactions/deleteTransaction/67b62c8ee6d42061caf7851a


### Get all Category 
GET http://localhost:5000/api/transactions/getCategory

### Get All Summary
GET http://localhost:5000/api/transactions/getAllSummary

### Get Category Summary
GET http://localhost:5000/api/transactions/getCatSummary

### Get All budgets
GET http://localhost:5000/api/budgets/getAllBudget

### Update any Budget 
POST http://localhost:5000/api/budgets/updateCategoryBudget
Content-Type: application/json

{
    "category":"Food",
     "amount": 5000
}